### ISSUE TITLE
[SmartRotate] Settings menu doesn’t work

### ISSUE THREAD

**Issue by ctalbot2004** [LaughingQuoll/Tweak-Issue-Tracker#9]
When I click “Ignore applications”, the list apps comes up twice, and when I click “Disable applications”, nothing happens. 

https://imgur.com/a/22lp52y

**Comment by Matrixnubee** [comment]
I’ve noticed this for a long time now.  Glad someone else sees it too.

**Comment by LaughingQuoll** [comment]
Found issue, has been fixed. Update pending.
